FROM TENSORFLOW_SOURCE_REPLACE
RUN pip install pandas
RUN pip install TFLearn h5py tqdm

COPY bin/run_jupyter.sh /
COPY bin/jupyter.key /
COPY bin/jupyter.pem /

WORKDIR /notebooks

EXPOSE 443

# CMD ["/bin/bash"]
CMD ["/run_jupyter.sh"]
